name: Deno CI/CD
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: "deno fmt --check"
        run: deno fmt --check --unstable

      - name: "deno lint"
        run: deno lint --unstable

      - name: "deno test"
        run: deno test --allow-all --unstable --no-check
